### ISSUE TITLE
about test

### ISSUE THREAD

**Issue by zhaoloulou** [itsyoavshalev/Image-Animation-with-Perturbed-Masks#2]
Hello, I want to use their own driver and source image to do the test, which is the test code

**Comment by itsyoavshalev** [comment]
No script for a single image.
You can run:
python run.py --config config/dataset_name.yaml --mode animate --checkpoint checkpoint_path

Of course, you will have to set the "root_dir" and "pairs_list" keys in dataset_name.yaml.

**Comment by zhaoloulou** [comment]
I see. Thank you very much

**Comment by zhaoloulou** [comment]
https://user-images.githubusercontent.com/42457505/123051314-39eaa900-d434-11eb-85c4-e42779d99fa5.mp4

python run.py --config config/dataset_name.yaml --mode animate --checkpoint checkpoint_path

The test result is this. Do you know what the problem is

**Comment by itsyoavshalev** [comment]
Maybe the pytorch version...
See README.md for the exact version we used.
