### ISSUE TITLE
hair details

### ISSUE THREAD

**Issue by MrYANG23** [itsyoavshalev/Image-Animation-with-Perturbed-Masks#3]
Hello, nice work . How long did it take to train 100 epochs? My training effect and hair details are not good. What is the reason

https://user-images.githubusercontent.com/38352877/128988574-33ffac4a-e87b-44d6-a30e-0adcc435c213.mp4

**Comment by MrYANG23** [comment]
hi， did you add patch gan loss and feture matching loss，

**Comment by itsyoavshalev** [comment]
1. 100 epochs took around one week (Titan RTX).
2. I'm not sure why you got such low-quality results, also the masks contain horizontal black lines, didn't encounter such a phenomenon.
3. Patch GAN - no, feature matching - yes.

**Comment by itsyoavshalev** [comment]
1. 100 epochs took around one week (Titan RTX).
2. I'm not sure why you got such low-quality results, also seems that the masks contain a lot of horizontal black lines, didn't encounter such a phenomenon.
3. Patch GAN - no, feature matching - yes.

**Comment by MrYANG23** [comment]
> 1. 100 epochs took around one week (Titan RTX).
> 2. I'm not sure why you got such low-quality results, also the masks contain horizontal black lines, didn't encounter such a phenomenon.
> 3. Patch GAN - no, feature matching - yes.


https://user-images.githubusercontent.com/38352877/133253979-1387357c-5009-40fe-a5d9-d7d9ada16e28.mp4


https://user-images.githubusercontent.com/38352877/133254150-2d88682c-b65d-432e-8ca9-4ac62025ffaa.mp4

thanks you for your reply .the video above is my new effect,which add some tricks,and the below is yours
as for the training time ,I have 4 TitanRTX ,but it takes 3 months to train 100 epochs. so i just trains 13 epcoh on voxdataset ,which about 17000 videos . why the training  times different .
did you set t
![image](https://user-images.githubusercontent.com/38352877/133255672-5d1260e3-a1b3-4b58-b6d3-dcf5e7fb0a9e.png)
he num_repeats=75 like this

**Comment by itsyoavshalev** [comment]
1. We didn't test the code with multiple GPUs, try running with a single GPU. It took one week.
2. Yes, we use the same values for VOX.
